/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account`; params?: Router.UnknownInputParams; } | { pathname: `/audit`; params?: Router.UnknownInputParams; } | { pathname: `/build-resume`; params?: Router.UnknownInputParams; } | { pathname: `/generate`; params?: Router.UnknownInputParams; } | { pathname: `/multi-result`; params?: Router.UnknownInputParams; } | { pathname: `/pricing`; params?: Router.UnknownInputParams; } | { pathname: `/referral-onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/report-bug`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cover-letter` | `/cover-letter`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/account`; params?: Router.UnknownOutputParams; } | { pathname: `/audit`; params?: Router.UnknownOutputParams; } | { pathname: `/build-resume`; params?: Router.UnknownOutputParams; } | { pathname: `/generate`; params?: Router.UnknownOutputParams; } | { pathname: `/multi-result`; params?: Router.UnknownOutputParams; } | { pathname: `/pricing`; params?: Router.UnknownOutputParams; } | { pathname: `/referral-onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/report-bug`; params?: Router.UnknownOutputParams; } | { pathname: `/result`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cover-letter` | `/cover-letter`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/account${`?${string}` | `#${string}` | ''}` | `/audit${`?${string}` | `#${string}` | ''}` | `/build-resume${`?${string}` | `#${string}` | ''}` | `/generate${`?${string}` | `#${string}` | ''}` | `/multi-result${`?${string}` | `#${string}` | ''}` | `/pricing${`?${string}` | `#${string}` | ''}` | `/referral-onboarding${`?${string}` | `#${string}` | ''}` | `/report-bug${`?${string}` | `#${string}` | ''}` | `/result${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cover-letter${`?${string}` | `#${string}` | ''}` | `/cover-letter${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/library${`?${string}` | `#${string}` | ''}` | `/library${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account`; params?: Router.UnknownInputParams; } | { pathname: `/audit`; params?: Router.UnknownInputParams; } | { pathname: `/build-resume`; params?: Router.UnknownInputParams; } | { pathname: `/generate`; params?: Router.UnknownInputParams; } | { pathname: `/multi-result`; params?: Router.UnknownInputParams; } | { pathname: `/pricing`; params?: Router.UnknownInputParams; } | { pathname: `/referral-onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/report-bug`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cover-letter` | `/cover-letter`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownInputParams; };
    }
  }
}
